// API client with static-mode fallback.
//
// Live mode talks to the school server (/api/*). When the server is
// unreachable (GitHub Pages static hosting), the app switches to static mode
// and serves the per-unit JSON files generated by `npm run gen-fallback`
// (client/src/data/units.json + client/src/data/units/<unitId>.json).
import unitsIndex from './data/units.json';

const BASE = '/api';
const STATIC_EVENT = 'api:static-mode';
const DEFAULT_UNIT = 'rime-of-the-ancient-mariner';

let staticMode = false;
let searchIndexPromise = null;

// In-memory cache for the read endpoints: navigating back and forth between
// unit pages re-issues the same GETs, and a session-scoped cache removes that
// churn. Mutations (admin edits, quiz attempts, flashcard marks, logout)
// invalidate the cache so nothing served is stale.
const GET_CACHE = new Map();

function clearGetCache() {
  GET_CACHE.clear();
}

function getToken() {
  return localStorage.getItem('token');
}

function setToken(token) {
  if (token) localStorage.setItem('token', token);
  else {
    localStorage.removeItem('token');
    clearGetCache();
  }
}

export function isStatic() {
  return staticMode;
}

// Synchronous access to the generated unit catalog (unit metadata only —
// content stays lazily loaded per unit).
export function getUnitCatalog() {
  return unitsIndex;
}

function enterStaticMode() {
  if (staticMode) return;
  staticMode = true;
  window.dispatchEvent(new CustomEvent(STATIC_EVENT));
}

async function request(path, options = {}) {
  const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) };
  const token = getToken();
  if (token) headers.Authorization = `Bearer ${token}`;

  let res;
  try {
    res = await fetch(`${BASE}${path}`, { ...options, headers });
  } catch {
    const err = new Error('Cannot reach the school server from this page.');
    err.static = true;
    throw err;
  }

  if (res.status === 401 && !path.startsWith('/auth/login') && !path.startsWith('/auth/register')) {
    setToken(null);
    window.dispatchEvent(new CustomEvent('auth:unauthorized'));
  }

  const contentType = (res.headers.get('content-type') || '').toLowerCase();
  if (!contentType.includes('json')) {
    const err = new Error('The school server is not available on this page.');
    err.static = true;
    throw err;
  }

  const body = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(body.error || `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  return body;
}

// Try the live API first; when it is unreachable (static hosting), serve the
// embedded unit data so every study page keeps working. Read calls are cached
// in memory for the session; pass options.noCache to always go to the network
// (quiz questions reshuffle server-side on purpose).
function withFallback(path, options = {}, makeFallback) {
  if (options.noCache) return fallbackOrRequest(path, options, makeFallback);
  const key = `${path}|${options.body || ''}`;
  if (!GET_CACHE.has(key)) {
    GET_CACHE.set(key, fallbackOrRequest(path, options, makeFallback));
  }
  return GET_CACHE.get(key);
}

async function fallbackOrRequest(path, options, makeFallback) {
  if (staticMode) return makeFallback();
  try {
    return await request(path, options);
  } catch (err) {
    if (err.static) {
      enterStaticMode();
      return makeFallback();
    }
    throw err;
  }
}

// ---- Static-mode data access (client/src/data/*) ----

async function loadUnitData(unitId) {
  try {
    const mod = await import(`./data/units/${unitId}.json`);
    return mod.default;
  } catch {
    const err = new Error(`Unit "${unitId}" is not available in this preview.`);
    err.status = 404;
    throw err;
  }
}

async function loadSearchIndex() {
  if (!searchIndexPromise) {
    searchIndexPromise = import('./data/search-index.json').then((m) => m.default);
  }
  return searchIndexPromise;
}

function unitMeta(unitId) {
  return unitsIndex.units.find((u) => u.id === unitId) || null;
}

function deriveContent(unitData) {
  const byCat = (cat) => unitData.content.filter((r) => r.category === cat);
  return {
    unitId: unitData.unit.id,
    summaries: byCat('summary'),
    themes: byCat('theme'),
    devices: byCat('device'),
    characters: byCat('character'),
    values: byCat('value'),
    analysis: byCat('analysis')
  };
}

function questionsFromUnit(unitData, category) {
  const rows = [...unitData.content].sort((a, b) => (a.category === b.category ? a.sortOrder - b.sortOrder : a.category.localeCompare(b.category)));
  if (category && category !== 'all') return rows.filter((r) => r.category === category);
  return rows;
}

function searchFallback(q, unitId) {
  const needle = String(q || '').trim().toLowerCase();
  if (!needle) return [];
  return loadSearchIndex().then((idx) =>
    idx.entries.filter((row) => {
      if (unitId && row.unitId !== unitId) return false;
      return [row.prompt, row.answer, row.notes]
        .filter(Boolean)
        .some((text) => String(text).toLowerCase().includes(needle));
    })
  );
}

const staticAuthError =
  'Sign-in is not available in this hosted preview — it runs without the school server. You can still study, search, quiz and use the flashcards as a guest.';

export const api = {
  getToken,
  setToken,

  register: async (data) => {
    try {
      return await request('/auth/register', { method: 'POST', body: JSON.stringify(data) });
    } catch (err) {
      if (err.static) throw new Error(staticAuthError);
      throw err;
    }
  },
  login: async (data) => {
    try {
      return await request('/auth/login', { method: 'POST', body: JSON.stringify(data) });
    } catch (err) {
      if (err.static) throw new Error(staticAuthError);
      throw err;
    }
  },
  me: async () => {
    try {
      return await request('/auth/me');
    } catch (err) {
      if (err.static) enterStaticMode();
      throw err;
    }
  },

  getUnits: () =>
    withFallback('/units', {}, () => ({
      books: unitsIndex.books.map((b) => ({
        ...b,
        units: b.unitIds.map((id) => unitsIndex.units.find((u) => u.id === id)).filter(Boolean)
      })),
      units: unitsIndex.units
    })),

  getUnitMeta: (unitId) => unitMeta(unitId || DEFAULT_UNIT),

  getContent: (unitId) => {
    const id = unitId || DEFAULT_UNIT;
    return withFallback(`/content?unit_id=${encodeURIComponent(id)}`, {}, async () => deriveContent(await loadUnitData(id)));
  },

  getQuestions: (unitId, category) => {
    const id = unitId || DEFAULT_UNIT;
    const cat = category && category !== 'all' ? `&category=${encodeURIComponent(category)}` : '';
    return withFallback(`/questions?unit_id=${encodeURIComponent(id)}${cat}`, {}, async () => ({
      questions: questionsFromUnit(await loadUnitData(id), category)
    }));
  },

  searchContent: (q, unitId) => {
    const scope = unitId ? `&unit_id=${encodeURIComponent(unitId)}` : '';
    return withFallback(`/content/search?q=${encodeURIComponent(q)}${scope}`, {}, async () => ({
      results: await searchFallback(q, unitId)
    }));
  },

  getQuizQuestions: (unitId, limit = 10) => {
    const id = unitId || DEFAULT_UNIT;
    return withFallback(`/quiz/questions?unit_id=${encodeURIComponent(id)}&limit=${limit}`, { noCache: true }, async () => {
      const data = await loadUnitData(id);
      const shuffled = [...data.quizQuestions].sort(() => Math.random() - 0.5);
      return { questions: shuffled.slice(0, limit) };
    });
  },

  submitAttempt: (score, total) => {
    clearGetCache();
    return request('/quiz/attempts', { method: 'POST', body: JSON.stringify({ score, total }) });
  },
  getAttempts: () => request('/quiz/attempts'),

  markKnown: (questionId, known) => {
    clearGetCache();
    return request(`/flashcards/${questionId}/known`, { method: 'POST', body: JSON.stringify({ known }) });
  },
  getFlashcardProgress: () => request('/flashcards/progress'),

  createQuestion: (data) => {
    clearGetCache();
    return request('/admin/questions', { method: 'POST', body: JSON.stringify(data) });
  },
  updateQuestion: (id, data) => {
    clearGetCache();
    return request(`/admin/questions/${id}`, { method: 'PUT', body: JSON.stringify(data) });
  },
  deleteQuestion: (id) => {
    clearGetCache();
    return request(`/admin/questions/${id}`, { method: 'DELETE' });
  },
  getQuestionsAdmin: (unitId) =>
    request(`/admin/questions${unitId ? `?unit_id=${encodeURIComponent(unitId)}` : ''}`),

  getQuizQuestionsAdmin: (unitId) =>
    request(`/admin/quiz-questions${unitId ? `?unit_id=${encodeURIComponent(unitId)}` : ''}`),
  createQuizQuestion: (data) => {
    clearGetCache();
    return request('/admin/quiz-questions', { method: 'POST', body: JSON.stringify(data) });
  },
  updateQuizQuestion: (id, data) => {
    clearGetCache();
    return request(`/admin/quiz-questions/${id}`, { method: 'PUT', body: JSON.stringify(data) });
  },
  deleteQuizQuestion: (id) => {
    clearGetCache();
    return request(`/admin/quiz-questions/${id}`, { method: 'DELETE' });
  }
};
